## Importing the libraries

In [3]:
import pandas as pd
import numpy as np


## Reading and splitting the dataset

In [6]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [7]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [9]:
X = dataset.iloc[:,0:-1].values

In [16]:
y = dataset.iloc[:,-1].values

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

## Implementing feature scaling

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc = StandardScaler()

In [20]:
X_train = sc.fit_transform(X_train)

In [21]:
X_test = sc.transform(X_test)

In [22]:
X_train

array([[ 0.27120298, -0.55340028],
       [ 0.0819916 , -0.29657994],
       [-1.33709376, -0.38218672],
       [-0.67485393,  0.13145397],
       [ 0.74423143, -1.23825453],
       [ 0.27120298, -0.23950875],
       [ 0.27120298,  0.24559634],
       [ 0.83883712,  1.18727094],
       [ 0.74423143, -0.35365113],
       [-0.958671  , -0.98143419],
       [ 0.74423143, -0.86729181],
       [-1.33709376, -0.4677935 ],
       [ 0.17659729, -0.41072231],
       [ 0.36580867, -0.52486469],
       [-0.958671  , -0.35365113],
       [-0.29643116, -0.011224  ],
       [-1.33709376, -0.4677935 ],
       [ 2.0687111 , -0.83875622],
       [ 0.83883712, -1.46653928],
       [-1.33709376,  0.35973872],
       [ 1.0280485 , -1.23825453],
       [-0.76945962, -1.55214607],
       [-0.86406531,  0.33120313],
       [ 0.0819916 ,  0.10291837],
       [ 0.17659729,  0.10291837],
       [-0.01261409, -0.011224  ],
       [-1.24248807, -1.09557656],
       [ 0.17659729, -0.41072231],
       [-0.67485393,

In [23]:
X_test

array([[-0.01261409, -0.58193588],
       [ 0.27120298, -0.35365113],
       [ 0.0819916 , -0.83875622],
       [-1.81012221, -1.32386132],
       [ 0.83883712, -0.69607825],
       [ 1.0280485 , -0.924363  ],
       [-0.01261409, -0.61047147],
       [-0.67485393,  1.32994891],
       [-1.43169945, -0.15390197],
       [-0.58024824,  1.815054  ],
       [ 1.87949972,  0.84484381],
       [-1.33709376, -1.26679013],
       [-0.01261409,  0.24559634],
       [-1.62091083,  0.47388109],
       [ 1.87949972, -0.9528986 ],
       [ 0.17659729, -0.32511553],
       [ 0.74423143, -1.3809325 ],
       [-0.76945962,  1.01605738],
       [-0.20182547, -0.32511553],
       [-1.43169945, -1.23825453],
       [-0.67485393, -0.09683078],
       [ 0.93344281, -0.86729181],
       [ 1.78489403, -1.09557656],
       [ 0.36580867, -0.03975959],
       [-1.05327669,  0.70216584],
       [-0.20182547,  0.10291837],
       [ 0.36580867,  2.21455232],
       [-1.05327669, -1.55214607],
       [ 0.17659729,

## Building the K-nearest neighbor model

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2 )

In [29]:
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting a new input

In [32]:
print(f"A person whose age is 25 and with an estimated salary of 29000: {classifier.predict([[25, 29000]])[0]}")

A person whose age is 25 and with an estimated salary of 29000: 1


## Comparing the predicted result with the actual result

In [35]:
y_pred = classifier.predict(X_test)

In [36]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]]
